services:
  nomad:
    image: hashicorp/nomad:1.9
    environment:
      NOMAD_ADDR: "http://localhost:4646"
    volumes:
      # - ./migration:/docker-entrypoint-initdb.d/
      - nomad:/var/lib/postgresql/data
    ports:
      - 9696:4646
  book-hub-api:
    image: back
    ports:
      - 4000:8080
    networks:
    - postgres2
  postgres:
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    networks:
      - postgres1
      - postgres2
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      # - ./migration:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "main@main.com"
      PGADMIN_DEFAULT_PASSWORD: "master"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "4001:80"
    networks:
      - postgres1
volumes:
  pg_data:
  pgadmin_data:

networks:
  postgres1:
    driver: overlay
  postgres2:
    driver: overlay
