version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bh-network

  bh-db:
    image: postgres:latest
    container_name: bh-db
    restart: always
    environment:
      POSTGRES_USER: bookhub
      POSTGRES_PASSWORD: bookhub123
      POSTGRES_DB: bookhubdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - bh-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      - bh-db
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - bh-network

  bh-backend:
    build:
      context: .
    container_name: bh-backend
    command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"
    networks:
      - bh-network
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/book-hub.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpassw:/etc/nginx/.htpassw:ro
    depends_on:
      - bh-backend
      - bh-db
      - pgadmin
    networks:
      - bh-network

  nomad:
    image: hashicorp/nomad:latest
    container_name: nomad
    command: agent -dev -bind=0.0.0.0 -client=false
    ports:
      - "4646:4646"
      - "4647:4647"
      - "4648:4648"
    networks:
      - bh-network
    depends_on:
      - mongo
      - bh-backend

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    depends_on:
      - bh-db
    environment:
      PGRST_DB_URI: postgres://bookhub:bookhub123@bh-db:5432/bookhubdb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
    networks:
      - bh-network

volumes:
  mongo_data:
  pg_data:

networks:
  bh-network:
    driver: bridge
