version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bh-network

  bh-db:
    image: postgres:latest
    container_name: bh-db
    restart: always
    environment:
      POSTGRES_USER: bookhub
      POSTGRES_PASSWORD: bookhub123
      POSTGRES_DB: bookhubdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bh-network

  pgadmin:
    image: dpage/pgadmin4:7.2
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5052:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bh-network
    depends_on:
      - bh-db

  bh-backend:
    build:
      context: .
    container_name: bh-backend
    command: ["npm", "run", "dev"]
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - bh-network

  bh-frontend:
    image: ghcr.io/book-hub-umsp/book-hub-app:latest
    container_name: bh-frontend
    ports:
      - "5002:3000"
    environment:
      GOOGLE_CLIENT_ID: "your-google-client-id"
      GOOGLE_CLIENT_SECRET: "your-google-client-secret"
      NEXTAUTH_SECRET: "your-nextauth-secret"
      NEXTAUTH_URL: "http://localhost:5002"
      MAIN_APP_VERSION: "latest"
    depends_on:
      - bh-backend
    networks:
      - bh-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/book-hub.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpassw:/etc/nginx/.htpassw:ro
    depends_on:
      - bh-backend
      - bh-frontend
      - bh-db
      - pgadmin
    networks:
      - bh-network

  nomad:
    image: hashicorp/nomad:1.9
    container_name: nomad
    command: agent -dev -bind=0.0.0.0 -client=false
    environment:
      - NOMAD_CLIENT=false
      - NOMAD_DISABLE_CGROUPS=true
    ports:
      - "9696:4646"
      - "4647:4647"
      - "4648:4648"
    volumes:
      - nomad_data:/var/lib/nomad
    depends_on:
      - bh-backend
      - mongo
    networks:
      - bh-network

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    networks:
      - bh-network

  postgrest:
    image: postgrest/postgrest
    container_name: postgrest
    ports:
      - "3000:3000"
    depends_on:
      - bh-db
    environment:
      PGRST_DB_URI: postgres://bookhub:bookhub123@bh-db:5432/bookhubdb
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
    networks:
      - bh-network

  migration-tool:
    build:
      context: ../bh-infrastructure-vault-base-setup/pmmt
      dockerfile: docker/Dockerfile
    container_name: migration-tool
    command:
      [
        "python", "main.py",
        "--name", "${DB_NAME}",
        "--type", "${DB_TYPE}",
        "--from", "${DB_FROM}",
        "--to", "${DB_TO}"
      ]
    environment:
      DB_DROP: ${DB_DROP}
      DB_MOCK1: ${DB_MOCK1}
      DB_MOCK2: ${DB_MOCK2}
    networks:
      - bh-network
    depends_on:
      - bh-db
      - vault

volumes:
  mongo_data:
  pg_data:
  pgadmin_data:
  nomad_data:

networks:
  bh-network:
    driver: bridge
