name: GraphQL Code Scan


on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigate to project directory
        run: cd bh-infrastructure  # Не знаю
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run GraphQL scan
        run: npm run graphql-scan
          echo "Scan results" > scan-results.txt

      - name: Save scan results
        run: echo "Scan successful" > scan-results.txt
        with:
          script: |
            const output = require('fs').readFileSync('scan-results.txt', 'utf8');
            const prNumber = context.payload.pull_request.number;
            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### GraphQL Code Scan Results:\n\n${output}`
            });
