name: Rotate Secrets


on:
  schedule:
    - cron: '0 3 * * 0'  # Каждое воскресенье в 3:00
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      secrets: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Nomad CLI
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install nomad
          
      - name: Execute rotation
        run: |
          chmod +x ./bh-infrastructure/scripts/rotate-secrets.sh
          ./bh-infrastructure/scripts/rotate-secrets.sh
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          NOMAD_ADDR: ${{ secrets.NOMAD_ADDR }}
